development:
  adapter: postgresql
  encoding: unicode
  database: friendsquote_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: friendsquote_test
  pool: 10
  username:
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: friendsquote_staging
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: friendsquote_production
  pool: 5
  username:
  password:
